### ISSUE TITLE
Unsupported platform for fsevents@1.2.4:  

### ISSUE THREAD

**Issue by llyy2330** [FallenMax/notepad.cc#3]
SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN notepad@1.0.0 No repository field.

**Comment by FallenMax** [comment]
@llyy2330 not a problem
