### ISSUE TITLE
why?

### ISSUE THREAD

**Issue by llyy2330** [FallenMax/notepad.cc#4]
[root@vultr notepad.cc]# npm run dev
npm ERR! Linux 3.10.0-862.3.2.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "dev"
npm ERR! node v6.14.3
npm ERR! npm  v3.10.10

npm ERR! missing script: dev
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /apps/notepad.cc/npm-debug.log
[root@vultr notepad.cc]#

**Comment by FallenMax** [comment]
@llyy2330 `README.md` was outdated. Fixed in https://github.com/FallenMax/notepad.cc/commit/f912855a8c4a22e35a917377b411a87c7bc198a0
