### ISSUE TITLE
Request for the latest package.json

### ISSUE THREAD

**Issue by AStogov** [FallenMax/notepad.cc#6]
I found that there are some differences between the nod_modules currently run on your website and the ones in your github repository. Could you please update your package.json file?
Meanwhile, I wonder how you establish an SSL connection due to I'm really new to node.js.
Thanks.

**Comment by FallenMax** [comment]
@AStogov  Sorry for seeing this late.  The source code here is up to date.  I'm using [yarn](http://yarnpkg.com/) other than `npm` to install dependencies. Maybe that's the cause of difference.

I'm using nginx to reverse-proxy all the requests, and SSL support is done in nginx config. Hope this could help you.
